solr_assocs:
  url: "https://solr.monarchinitiative.org/solr/golr"
  timeout: 60
amigo_solr_assocs:
  url: "http://golr.geneontology.org/solr"
  timeout: 15
solr_search:
  url: "https://solr.monarchinitiative.org/solr/search"
  timeout: 15
lay_person_search:
  url: "https://solr.monarchinitiative.org/solr/hpo-pl"
  timeout: 15
amigo_solr_search:
  url: "http://golr.geneontology.org/solr"
  timeout: 15
sparql:
  url: "http://rdf.geneontology.org/sparql"
  timeout: 30
scigraph_ontology:
  url: "https://scigraph-ontology.monarchinitiative.org/scigraph/"
  timeout: 15
scigraph_data:
  url: "https://scigraph-data.monarchinitiative.org/scigraph"
  timeout: 15
owlsim2:
  url: "https://legacy.monarchinitiative.org/owlsim/"
  timeout: 45
owlsim3:
  url: "http://owlsim3.monarchinitiative.org/api/"
  timeout: 15
use_amigo_for:
  - function
ontologies:
  - id: magic1234
    handle: pato
    pre_load: true
# taxon_restriction: 
#   - NCBITaxon:10090
#   - NCBITaxon:9606
#   - NCBITaxon:10116
#   - NCBITaxon:559292
#   - NCBITaxon:6239
#   - NCBITaxon:7955
#   - NCBITaxon:7227
